### ISSUE TITLE
Support for rulesets hosted in private github repos

### ISSUE THREAD

**Issue by j-mccloskey** [dweber019/backstage-plugin-api-docs-spectral-linter#61]
Hi 👋 

Thanks for the plugin!

I ran into some trouble fetching a ruleset that is in a private github repository. Is there a way to configure the plugin to use a token to gain access?

**Comment by dweber019** [comment]
Hi @j-mccloskey 

The plugin doesn't deliver this out of box.
But you could use the proxy plugin for this => https://backstage.io/docs/plugins/proxying

The proxy config could look something like this
```yaml
proxy:
  endpoints:
    '/spectral-linter/ruleset.yaml':
      target: http://private.repo.com/ruleset.yaml
      headers:
        Authorization: ${TOKEN}
```

And for the linter configuration something like
```yaml
spectralLinter:
  openApiRulesetUrl: http://localhost:7007/api/proxy/spectral-linter/ruleset.yaml
```

Just be aware that everyone can now access your `ruleset.yaml` as there is no front facing security on the proxy.
